---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install vector
  hosts: vector
  roles:
    - vector-role


- name: Install nginx
  handlers:
    - name: Restart nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: Create nginx config
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "0755"
        owner: "nginx"
        group: "nginx"
      notify: Restart nginx service

    - name: Copy clickhouse to www
      ansible.builtin.copy:
        src: "/tmp/lighthouse"
        dest: "/var/www/"
        remote_src: true
        mode: "0755"
        owner: "nginx"
        group: "nginx"

- name: Install git for lighthouse
  hosts: lighthouse
  tasks:
    - name: Lighthouse - install git
      become: true
      ansible.builtin.apt:
        name: git
        state: present

- name: Install lighthouse
  hosts: lighthouse
  roles:
    - lighthouse-role
